Repository hmcts/wa-proto-frontend, pull requests merged in 2020-10, with the labels that each got.

#19 Rwa 110 2
  src/main/app.ts
  src/main/assets/scss/filter-by-location.scss
  src/main/controllers/filterTasksByLocations.ts
  src/main/controllers/myCaseWork.ts
  src/main/data/myCaseWorkData.ts
  src/main/models/location.ts
  src/main/models/myCaseWorkModel.ts
  src/main/routes/myCaseWork.ts
  src/main/views/components/filter-by-location.njk
  src/main/views/my-case-work.njk
  src/test/unit/controllers/filterTasksByLocations.test.ts
  src/test/unit/controllers/myCaseWork.test.ts
  src/test/unit/routes/myCaseWork.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-19

#18 add filter by location details component
  src/main/app.ts
  src/main/assets/scss/filter-by-location.scss
  src/main/assets/scss/main.scss
  src/main/assets/scss/my-case-work.scss
  src/main/client/detail-actions/detail-actions.js
  src/main/client/filter-by-location/listbox-rearrangeable.js
  src/main/client/filter-by-location/listbox.js
  src/main/client/filter-by-location/toolbar.js
  src/main/client/filter-by-location/utils.js
  src/main/client/sortable-table/jquery.js
  src/main/client/sortable-table/sortable-table.js
  src/main/controllers/filterTasksByLocations.ts
  src/main/controllers/myCaseWork.ts
  src/main/data/myCaseWorkData.ts
  src/main/models/location.ts
  src/main/models/myCaseWorkModel.ts
  src/main/routes/myCaseWork.ts
  src/main/views/components/filter-by-location.njk
  src/main/views/includes/detail-actions-scripts.njk
  src/main/views/includes/filter-by-location-scripts.njk
  src/main/views/includes/sortable-table-scripts.njk
  src/main/views/my-case-work.njk
  src/test/unit/controllers/filterTasksByLocations.test.ts
  src/test/unit/controllers/myCaseWork.test.ts
  src/test/unit/routes/myCaseWork.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-18

#22 make due date bold
  src/main/assets/scss/main.scss
  src/main/assets/scss/my-case-work.scss
  src/main/assets/scss/task-list.scss
  src/main/client/detail-actions/detail-actions.js
  src/main/models/myCaseWorkModel.ts
  src/main/views/components/filter-by-location.njk
  src/main/views/components/my-tasks.njk
  src/main/views/task-list.njk
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-22

#25 added redirect and completion of tasks
  src/main/controllers/claimTaskController.ts
  src/main/controllers/completeTaskFromMyTasks.ts
  src/main/controllers/unClaimTaskController.ts
  src/main/routes/taskList.ts
  src/main/views/components/my-tasks.njk
  src/test/unit/controllers/completeTaskByCaseRef.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-25

#26 Task/rwa 132 fixes
  src/main/assets/scss/header.scss
  src/main/assets/scss/task-list.scss
  src/main/views/components/my-tasks.njk
  src/main/views/my-cases.njk
  src/main/views/task-list.njk
  src/main/views/template.njk
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-26

#27 updates for assign link
  src/main/controllers/claimTaskController.ts
  src/main/views/components/my-tasks.njk
  src/test/unit/controllers/claimTaskController.test.ts
  src/test/unit/routes/taskList.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-27

#24 Task/rwa 135
  charts/wa-proto-frontend/Chart.yaml
  charts/wa-proto-frontend/values.preview.template.yaml
  charts/wa-proto-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/.gitignore
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
  jest.config.js
  package.json
  sonar-project.properties
  src/main/app.ts
  src/main/services/setupSecrets.ts
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-24

#28 reassign a task
  package.json
  src/main/client/detail-actions/detail-actions.js
  src/main/controllers/reassignTaskController.ts
  src/main/models/caseworker.ts
  src/main/models/myCaseWorkModel.ts
  src/main/models/task.ts
  src/main/routes/taskList.ts
  src/main/views/macros/createDropdown.njk
  src/main/views/macros/filter-by-location.njk
  src/main/views/macros/my-tasks.njk
  src/main/views/macros/status-bar.njk
  src/main/views/my-cases.njk
  src/main/views/reassign-task.njk
  src/main/views/task-list.njk
  src/test/unit/controllers/reassignTask.test.ts
  src/test/unit/routes/taskList.test.ts
  yarn.lock
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-28

#29 destroy session when sign out button is clicked
  src/main/controllers/userControllers.ts
  src/main/routes/signOut.ts
  src/main/views/task-list.njk
  src/main/views/template.njk
  src/test/unit/controllers/userController.ts
  src/test/unit/routes/myCases.test.ts
  src/test/unit/routes/userSignOut.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-29

#32 date ordering and available tasks redirect
  src/main/controllers/claimTaskController.ts
  src/main/controllers/filterTasksByLocations.ts
  src/main/controllers/taskListController.ts
  src/main/controllers/unClaimTaskController.ts
  src/main/utils/order-date-utils.ts
  src/main/views/task-list.njk
  src/test/unit/controllers/claimTaskController.test.ts
  src/test/unit/controllers/filterTasksByLocations.test.ts
  src/test/unit/controllers/taskListController.ts
  src/test/unit/controllers/unClaimTaskController.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-32

#34 added cases for all locations
  src/main/controllers/claimTaskController.ts
  src/main/controllers/filterTasksByLocations.ts
  src/main/controllers/reassignTaskController.ts
  src/main/controllers/taskListController.ts
  src/main/controllers/unClaimTaskController.ts
  src/main/models/myCaseWorkModel.ts
  src/test/unit/controllers/filterTasksByLocations.test.ts
  src/test/unit/controllers/reassignTask.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-34

#36 done button fix and task list change
  src/main/controllers/filterTasksByLocations.ts
  src/main/models/myCaseWorkModel.ts
  src/main/models/task.ts
  src/test/unit/controllers/filterTasksByLocations.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-36

#37 add one unassigned task
  src/main/client/detail-actions/detail-actions.js
  src/main/controllers/claimTaskController.ts
  src/main/controllers/completeTaskFromMyTasksController.ts
  src/main/controllers/reassignTaskController.ts
  src/main/models/myModel.ts
  src/main/views/macros/task-manager-tasks.njk
  src/main/views/reassign-task.njk
  src/main/views/task-manager.njk
  src/test/unit/controllers/completeTaskByCaseRefController.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-37

#33 Feature/rwa 124
  src/main/app.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/task-manager.scss
  src/main/client/detail-actions/detail-actions.js
  src/main/controllers/claimTaskController.ts
  src/main/controllers/completeTaskFromMyTasksController.ts
  src/main/controllers/filterTasksByLocationsController.ts
  src/main/controllers/myCasesController.ts
  src/main/controllers/reassignTaskController.ts
  src/main/controllers/taskManagerController.ts
  src/main/models/myCaseWorkModel.ts
  src/main/models/myModel.ts
  src/main/models/taskManager/taskManagerCaseWorker.ts
  src/main/models/taskManager/taskManagerLocation.ts
  src/main/models/taskManager/taskManagerModel.ts
  src/main/routes/myCases.ts
  src/main/routes/taskList.ts
  src/main/routes/taskManager.ts
  src/main/views/macros/task-manager-tasks.njk
  src/main/views/my-cases.njk
  src/main/views/reassign-task.njk
  src/main/views/task-list.njk
  src/main/views/task-manager.njk
  src/main/views/template.njk
  src/test/unit/controllers/completeTaskByCaseRef.ts
  src/test/unit/controllers/completeTaskByCaseRefController.test.ts
  src/test/unit/controllers/filterTasksByLocationsController.test.ts
  src/test/unit/controllers/myCasesController.test.ts
  src/test/unit/controllers/reassignTaskController.test.ts
  src/test/unit/controllers/taskListController.test.ts
  src/test/unit/controllers/taskManagerController.test.ts
  src/test/unit/routes/myCases.test.ts
  src/test/unit/routes/taskList.test.ts
  src/test/unit/routes/taskManager.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-33

#39 add All locations to the menu and filter by all locations
  src/main/controllers/taskManagerController.ts
  src/main/models/myModel.ts
  src/main/models/taskManager/taskManagerModel.ts
  src/test/unit/controllers/taskManagerController.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-39

#38 updated reassign
  src/main/controllers/reassignTaskController.ts
  src/test/unit/controllers/reassignTaskController.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-38

#41 removing complete task from all lists
  src/main/controllers/completeTaskFromMyTasksController.ts
  src/test/unit/controllers/completeTaskByCaseRefController.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-41

#40 Feature/rwa 167 reassign task
  src/main/app.ts
  src/main/controllers/reassignTaskController.ts
  src/main/controllers/taskManagerController.ts
  src/main/models/myModel.ts
  src/main/routes/taskList.ts
  src/main/views/task-manager.njk
  src/test/unit/controllers/completeTaskByCaseRefController.test.ts
  src/test/unit/controllers/reassignTaskController.test.ts
  src/test/unit/controllers/taskManagerController.test.ts
  src/test/unit/routes/taskList.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-40

#42 task list fix
  src/main/controllers/reassignTaskController.ts
  src/test/unit/controllers/reassignTaskController.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-42

#43 removal of double entry
  src/main/models/myModel.ts
  src/test/unit/controllers/reassignTaskController.test.ts
Labels: ns:wa, prd:wa, rel:wa-proto-frontend-pr-43
